#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /{wildcard}
    controller: App\Controller\DefaultController::index
    requirements:
        wildcard: .*
